import { Coupon } from '@/types/coupon';

/**
 * ダミークーポンデータ
 */
export const dummyCoupons: Coupon[] = [
  {
    id: '1',
    source: 'AliExpress',
    title: '全商品10%オフクーポン',
    description: '初回購入限定で全商品が10%オフになるクーポンです',
    category: 'shopping',
    expiresAt: new Date('2026-02-28'),
    url: 'https://www.aliexpress.com/coupon',
    acquiredAt: new Date('2026-01-15'),
    tags: ['初回限定', '全商品対象'],
  },
  {
    id: '2',
    source: 'AliExpress',
    title: '5000円以上で送料無料',
    description: '5000円以上のお買い上げで送料が無料になります',
    category: 'shopping',
    expiresAt: new Date('2026-01-31'),
    url: 'https://www.aliexpress.com/coupon/shipping',
    acquiredAt: new Date('2026-01-10'),
    tags: ['送料無料'],
  },
  {
    id: '3',
    source: 'じゃらん',
    title: '宿泊料金20%オフクーポン',
    description: '対象宿泊施設の料金が20%オフになるクーポンです',
    category: 'travel',
    expiresAt: new Date('2026-03-31'),
    url: 'https://www.jalan.net/coupon',
    acquiredAt: new Date('2026-01-12'),
    tags: ['宿泊', '国内旅行'],
  },
  {
    id: '4',
    source: 'Uber Eats',
    title: '初回注文1500円オフ',
    description: '初回注文時に使える1500円オフクーポン',
    category: 'food',
    expiresAt: new Date('2026-02-15'),
    url: 'https://www.ubereats.com/promo',
    acquiredAt: new Date('2026-01-18'),
    tags: ['初回限定', 'デリバリー'],
  },
  {
    id: '5',
    source: 'Amazon',
    title: 'プライム会員限定500円クーポン',
    description: 'プライム会員限定で使える500円オフクーポン',
    category: 'shopping',
    expiresAt: new Date('2026-01-25'),
    url: 'https://www.amazon.co.jp/coupon',
    acquiredAt: new Date('2026-01-05'),
    tags: ['プライム会員限定'],
  },
  {
    id: '6',
    source: 'Netflix',
    title: '初月無料トライアル',
    description: '新規登録で初月無料でお試しいただけます',
    category: 'entertainment',
    expiresAt: new Date('2026-12-31'),
    url: 'https://www.netflix.com/trial',
    acquiredAt: new Date('2026-01-01'),
    tags: ['初回限定', 'サブスク'],
  },
  {
    id: '7',
    source: '楽天',
    title: '楽天スーパーセール特別クーポン',
    description: 'スーパーセール期間中に使える特別クーポン',
    category: 'shopping',
    expiresAt: new Date('2026-02-10'),
    url: 'https://event.rakuten.co.jp/supersale/',
    acquiredAt: new Date('2026-01-08'),
    tags: ['期間限定', 'セール'],
  },
  {
    id: '8',
    source: 'スターバックス',
    title: 'ドリンク1杯無料クーポン',
    description: 'お好きなドリンク1杯が無料になるクーポン',
    category: 'food',
    expiresAt: new Date('2026-01-30'),
    url: 'https://www.starbucks.co.jp/coupon',
    acquiredAt: new Date('2026-01-19'),
    tags: ['ドリンク', '無料'],
  },
];
